parameters:
  - name: isPublish
    type: boolean
    default : false

jobs:
  - job: Build
    timeoutInMinutes: 120
    displayName: Build Hermes
    dependsOn: 
      - ${{ if parameters.isPublish }}:
        - Setup
    strategy:
      matrix:
        ReleaseX64Uwp:
          BuildConfiguration: release
          BuildPlatform: x64
          BuildAppPlatform: uwp
        ReleaseX86Uwp:
          BuildConfiguration: release
          BuildPlatform: x86
          BuildAppPlatform: uwp
        ReleaseArm64Uwp:
          BuildConfiguration: release
          BuildPlatform: arm64
          BuildAppPlatform: uwp
        ReleaseX64Win32:
          BuildConfiguration: release
          BuildPlatform: x64
          BuildAppPlatform: win32
        ReleaseX86Win32:
          BuildConfiguration: release
          BuildPlatform: x86
          BuildAppPlatform: win32
        ReleaseArm64Win32:
          BuildConfiguration: release
          BuildPlatform: arm64
          BuildAppPlatform: win32
        ReleaseArm64ECWin32:
          BuildConfiguration: release
          BuildPlatform: arm64ec
          BuildAppPlatform: win32

    variables:
      semanticVersion: $[ dependencies.Setup.outputs['setVersions.semanticVersion'] ]
      fileVersion: $[ dependencies.Setup.outputs['setVersions.fileVersion'] ]
      # To fake building hermes for faster debugging
      fakeBuild: true

    ${{ if parameters.isPublish }}:
      templateContext:
        outputs:
          - output: buildArtifacts
            PathtoPublish: $(Build.ArtifactStagingDirectory)
            artifactName: HermesArtifacts
    steps:
      - task: PowerShell@2
        displayName: Run the build script for publish
        inputs:
          targetType: filePath
          filePath: $(Build.SourcesDirectory)\.ado\scripts\cibuild.ps1
          arguments:
            -SourcesPath:$(Build.SourcesDirectory)
            -OutputPath:$(Build.ArtifactStagingDirectory)
            -Platform:$(BuildPlatform)
            -Configuration:$(BuildConfiguration)
            -AppPlatform:$(BuildAppPlatform)
            -ReleaseVersion:"$(semanticVersion)"
            -FileVersion:"$(fileVersion)"
            -FakeBuild:$$(fakeBuild)

      - ${{ if parameters.isPublish }}:
        - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@5
          displayName: CodeSign Binaries
          condition: not(eq(variables['Build.Reason'], 'PullRequest'))
          inputs:
            connectedServiceName: 'ESRP-JSHost3'
            appRegistrationClientId: '0a35e01f-eadf-420a-a2bf-def002ba898d'
            appRegistrationTenantId: 'cdc5aeea-15c5-4db6-b079-fcadd2505dc2'
            authAKVName: 'OGX-JSHost-KV'
            authCertName: 'OGX-JSHost-Auth4'
            authSignCertName: 'OGX-JSHost-Sign3'
            folderPath: $(Build.ArtifactStagingDirectory)
            # Recursively finds files matching these patterns:
            pattern: |
              **/hermes.dll
              **/hermes.exe
              **/hermesc.exe
            useMinimatch: true
            signConfigType: inlineSignParams
            inlineOperation: |
              [
                {
                  "KeyCode" : "CP-230012",
                  "OperationCode" : "SigntoolSign",
                  "Parameters" : {
                    "OpusName" : "Microsoft",
                    "OpusInfo" : "http://www.microsoft.com",
                    "FileDigest" : "/fd \"SHA256\"",
                    "PageHash" : "/NPH",
                    "TimeStamp" : "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                  },
                  "ToolName" : "sign",
                  "ToolVersion" : "1.0"
                },
                {
                  "KeyCode" : "CP-230012",
                  "OperationCode" : "SigntoolVerify",
                  "Parameters" : {},
                  "ToolName" : "sign",
                  "ToolVersion" : "1.0"
                }
              ]

      - script: echo TODO - Add Tests here
        displayName: '[Test] - To be Added via bug #77'

      # Make symbols available through http://symweb.
      - task: PublishSymbols@2
        displayName: Publish symbols
        condition: not(eq(variables['Build.Reason'], 'PullRequest'))
        inputs:
          SearchPattern: $(Build.ArtifactStagingDirectory)/**/*.pdb
          SymbolServerType: TeamServices
          UseNetCoreClientTool: true

      - script: |
          ls -R $(Build.ArtifactStagingDirectory)
        displayName: Show all files in the Build.ArtifactStagingDirectory

  - job: CreateNuGet
    dependsOn:
      - Build
    displayName: Create Nuget packages
    ${{ if parameters.isPublish }}:
      templateContext:
        outputs:
          - output: pipelineArtifact
            artifactName: published-packages
            PathtoPublish: $(Build.ArtifactStagingDirectory)
            targetPath: $(Build.StagingDirectory)\build\pkg
    steps:
      - checkout: none

      # The commit tag in the nuspec requires that we use at least nuget 4.6
      - task: NuGetToolInstaller@0
        inputs:
          versionSpec: ">=4.6.0"

      - task: DownloadBuildArtifacts@0
        displayName: Download Build outputs
        inputs:
          artifactName: HermesArtifacts
          downloadPath: $(System.DefaultWorkingDirectory)

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $Version = (Get-Content (Join-Path $(System.DefaultWorkingDirectory) "HermesArtifacts\version") | Out-String).Trim()
            Write-Host "##vso[task.setvariable variable=Version]$Version"

      - task: NuGetCommand@2
        displayName: 'NuGet Pack'
        inputs:
          command: pack
          packagesToPack: $(System.DefaultWorkingDirectory)\HermesArtifacts\Microsoft.JavaScript.Hermes.nuspec
          packDestination: $(Build.StagingDirectory)\build\pkg
          buildProperties: CommitId=$(Build.SourceVersion);nugetroot=$(System.DefaultWorkingDirectory)\HermesArtifacts;RepoUri=$(Build.Repository.Uri)
          versioningScheme: byEnvVar
          versionEnvVar: Version

      - task: NuGetCommand@2
        displayName: 'NuGet Fat Pack'
        inputs:
          command: pack
          packagesToPack: $(System.DefaultWorkingDirectory)\HermesArtifacts\Microsoft.JavaScript.Hermes.Fat.nuspec
          packDestination: $$(Build.StagingDirectory)\build\pkg
          buildProperties: CommitId=$(Build.SourceVersion);nugetroot=$(System.DefaultWorkingDirectory)\HermesArtifacts;RepoUri=$(Build.Repository.Uri)
          versioningScheme: byEnvVar
          versionEnvVar: Version

      - ${{ if parameters.isPublish }}:
        - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@5
          displayName: CodeSign NuGets
          condition: not(eq(variables['Build.Reason'], 'PullRequest'))
          inputs:
            connectedServiceName: 'ESRP-JSHost3'
            appRegistrationClientId: '0a35e01f-eadf-420a-a2bf-def002ba898d'
            appRegistrationTenantId: 'cdc5aeea-15c5-4db6-b079-fcadd2505dc2'
            authAKVName: 'OGX-JSHost-KV'
            authCertName: 'OGX-JSHost-Auth4'
            authSignCertName: 'OGX-JSHost-Sign3'
            folderPath: $(Build.StagingDirectory)\build\pkg
            pattern: |
              **/Microsoft.JavaScript.Hermes.*.nupkg
              **/Microsoft.JavaScript.Hermes.Fat.*.nupkg
            useMinimatch: true
            signConfigType: inlineSignParams
            inlineOperation: |
              [
                {
                  "KeyCode" : "CP-401405",
                  "OperationCode" : "NuGetSign",
                  "Parameters" : {},
                  "ToolName" : "sign",
                  "ToolVersion" : "1.0"
                },
                {
                  "KeyCode" : "CP-401405",
                  "OperationCode" : "NuGetVerify",
                  "Parameters" : {},
                  "ToolName" : "sign",
                  "ToolVersion" : "1.0"
                }
              ]
