# Currently we use a temprorary versioning scheme where it starts with "0.1.".
name: temp_0.1.$(Rev:r)

pr: none
trigger:
  - main

extends:
  template: common.yml@self
   parameters:
-    isPublish: true
