#
# Entry point for the CI builds that are run after merging PRs.
#

# The name is parsed by setVersionNumber.js script which then updates the name of the run.
#
# The release branch versions "rnw/*" start with the release number
# such as "0.69." or "0.70." and follow the revision number.
# name: 0.70.$(Rev:r)
#
# The main branch pre-release versions start with "0.0."
# and follow the date and revision number.
name: 0.0.$(Date:yyMM.d)$(Rev:rrr)

pr: none
trigger:
  - main
  - rnw/*

variables:
  - name: tags
    value: production,externalfacing

extends:
  template: build-and-pack.yml@self
  parameters:
    MustPublish: true
