#
# Entry point for the CI builds that are run after merging PRs.
#

name: 0.0.$(Date:yyMM.d)$(Rev:rrr)

pr: none
trigger:
  - main
  - rnw/*

variables:
  - name: tags
    value: production,externalfacing

extends:
  template: build-and-pack.yml@self
  parameters:
    isPublish: true
