# This rev-count is used in the Setup job as a monotonic increasing number
# Be carefull if you edit the name as it can accidentally reset the count
# see: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml#tokens
name: Unversioned-$(Rev:r)

pr: none
trigger:
  - main

pool: OE-OfficePublic

variables:
  - group: Hermes-Windows Secrets
  - group: InfoSec-SecurityResults
  - name: ArtifactServices.Symbol.AccountName
    value: microsoft
  - name: ArtifactServices.Symbol.PAT
    value: $(pat-symbols-publish-microsoft)
  - name: tags
    value: production,externalfacing

jobs:
  - job: Setup
    steps:
      - script: node .ado/scripts/setVersionNumber.js

  - template: jobs.yml
    parameters:
      dependsOnSetup: true