#
# The Release pipeline entry point.
# It releases NuGet packages to the public ms/react-natve ADO feed and to the NuGet.org feed.
#

trigger: none
name: Release $(Date:yyyyMMdd).$(Rev:r)

resources:
  pipelines:
  - pipeline: _microsoft.hermes-windows
    project: 'ISS'
    source: 'microsoft.hermes-windows.ci'
    trigger:
      branches:
        include:
        - main
        - rnw/*

  repositories:
  - repository: CustomPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/OfficePipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/Office.Official.PipelineTemplate.yml@CustomPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      vmImage: windows-latest
      os: windows

    stages:
    - stage: ms_react_native_nuget_publish
      displayName: Nuget ms/react-native feed

      jobs:
      - job: ms_react_native_nuget_job
        displayName: Publish Nuget to ms/react-native
        condition: succeeded()
        timeoutInMinutes: 0

        templateContext:
          inputs:
          - input: pipelineArtifact
            pipeline: _microsoft.hermes-windows
            artifactName: published-packages
            targetPath: $(Pipeline.Workspace)\published-packages

        steps:
        - script: dir /S $(Pipeline.Workspace)\published-packages
          displayName: Show directory contents

        - script: dotnet nuget list source
          displayName: Show Nuget sources

        - task: 1ES.PublishNuGet@1
          displayName: NuGet push
          inputs:
            useDotNetTask: true
            packageParentPath: '$(Pipeline.Workspace)/published-packages'
            packagesToPush: '$(Pipeline.Workspace)/published-packages/Microsoft.JavaScript.Hermes.*.nupkg'
            nuGetFeedType: external
            publishFeedCredentials: 'Nuget - ms/react-native-public'
            externalEndpoint: 'Nuget - ms/react-native-public'
            publishPackageMetadata: true

    - stage: nuget_org_publish
      displayName: Nuget nuget.org feed

      jobs:
      - job: nuget_org_job
        displayName: Publish Nuget to nuget.org
        condition: succeeded()
        timeoutInMinutes: 0

        templateContext:
          inputs:
          - input: pipelineArtifact
            pipeline: _microsoft.hermes-windows
            artifactName: published-packages
            targetPath: '$(Pipeline.Workspace)/published-packages'

        steps:
        - task: AzureKeyVault@2
          inputs:
            azureSubscription: ESRP-JSHost3
            KeyVaultName: OGX-JSHost-KV
            SecretsFilter: 'OGX-JSHost-Nuget-org-API-key-Microsoft-JavaScript-NodeApi'
            RunAsPreJob: true

        - task: NuGetToolInstaller@1
          displayName: 'Use NuGet'

        - script: 'nuget.exe SetApiKey $(OGX-JSHost-Nuget-org-API-key-Microsoft-JavaScript-NodeApi)'
          displayName: 'NuGet SetApiKey (nuget.org)'

        - script: dir /S $(Pipeline.Workspace)\published-packages
          displayName: Show directory contents

        - script: >
            nuget.exe push
            $(Pipeline.Workspace)\published-packages\Microsoft.JavaScript.Hermes.*.nupkg
            -Source https://api.nuget.org/v3/index.json
            -SkipDuplicate
            -NonInteractive
            -Verbosity Detailed
          displayName: 'NuGet push (nuget.org)'
