#
# Entry point for the PR builds that are run to validate PR.
#

name: 0.0.$(Date:yyMM.d)$(Rev:rrr)

trigger: none
pr:
  - main
  - rnw/*

extends:
  template: build-and-pack.yml@self
  parameters:
    # Make sure that the PR builds do not publish signed packages.
    isPublish: false
